spring.application.name=videoclub

server.port=8080

spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.bxasmoppmlbedlpwogmd
spring.datasource.password=Proyecto01.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false